import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { after, test } from "node:test";
import { parseConfig } from "../src/config.ts";
import { branchName, commitMessage, openPullRequest, prBody } from "../src/deliver/pr.ts";
import type { MigrationOutcome } from "../src/migrate/index.ts";
import type { ChangeEntry, ImpactItem } from "../src/types.ts";

const execFileAsync = promisify(execFile);
const SRC = path.join(import.meta.dirname, "..", "src");
const tempDirs: string[] = [];

after(() => {
  for (const dir of tempDirs) fs.rmSync(dir, { recursive: true, force: true });
});

const ITEM: ImpactItem = {
  id: "http_api.parcelio.test-abc",
  entryId: "e1",
  integrationId: "http:api.parcelio.test",
  relevant: true,
  risk: "high",
  deadline: "2027-01-15",
  summary: "The tracking endpoint is deprecated",
  whatChanged: "GET /v1/shipments/{id}/track is deprecated in favour of /v2/tracking.",
  affected: [{ file: "shipping/client.py", line: 53, reason: "calls the deprecated operation" }],
  migrationSteps: ["Move to /v2/tracking"],
  dependencyChanges: [],
  validationHints: [],
  analyzedBy: "anthropic/claude-opus-5",
};

const ENTRY: ChangeEntry = {
  id: "e1",
  integrationId: "http:api.parcelio.test",
  source: "upstream/openapi.v2.json",
  kind: "openapi",
  title: "Operation deprecated",
  body: "…",
  tags: ["deprecation"],
  identifiers: [],
};

function outcome(overrides: Partial<MigrationOutcome> = {}): MigrationOutcome {
  return {
    integrationId: "http:api.parcelio.test",
    items: [ITEM],
    status: "validated",
    summary: "Moved the tracking call to /v2/tracking and renamed the parameter.",
    validation: {
      passed: true,
      checks: [
        { name: "`python3 -m unittest`", passed: true, details: "OK" },
        { name: "residual usage", passed: true, details: "the old call is gone" },
        { name: "HTTP contract", passed: true, details: "3 call sites, 0 errors" },
      ],
    },
    patch: "diff --git a/shipping/client.py b/shipping/client.py\n",
    patchFile: "/tmp/does-not-matter.patch",
    changedFiles: ["shipping/client.py", "tests/test_client.py"],
    attempts: 1,
    transcriptFile: "/tmp/transcript.jsonl",
    ...overrides,
  };
}

test("the branch name is stable per integration and day", () => {
  const day = new Date("2026-09-18T10:00:00Z");
  assert.equal(branchName(outcome(), day), "acb/api.parcelio.test/2026-09-18");
  assert.equal(branchName(outcome(), day), branchName(outcome(), day));
});

test("the commit message is conventional and says it needs review", () => {
  const message = commitMessage(outcome());
  assert.match(message.split("\n")[0], /^fix\(api\): migrate api\.parcelio\.test/);
  assert.match(message, /Requires human review/);

  const many = commitMessage(outcome({ items: [ITEM, { ...ITEM, id: "b", entryId: "e2" }] }));
  assert.match(many.split("\n")[0], /\(2 upstream changes\)/);
});

test("the pull request body carries the analysis, the validation and the banner", () => {
  const body = prBody({
    config: parseConfig({ validate: { commands: ["python3 -m unittest"] } }, "/repo"),
    outcome: outcome(),
    entries: [ENTRY],
    reportFile: "/repo/.acb/reports/2026-09-18-impact.md",
  });

  assert.match(body, /Generated by acb/);
  assert.match(body, /A human must review this before merging/);
  assert.match(body, /deadline \*\*2027-01-15\*\*/);
  assert.match(body, /Source: upstream\/openapi\.v2\.json/);
  assert.match(body, /Assessed by: anthropic\/claude-opus-5/);
  assert.match(body, /shipping\/client\.py:53/);
  assert.match(body, /\| residual usage \| ✅ passed \|/);
  assert.match(body, /python3 -m unittest/);
  assert.match(body, /acb contract http:api\.parcelio\.test/);
  assert.match(body, /2026-09-18-impact\.md/);
  assert.match(body, /does not merge, enable auto-merge, or push to the default branch/);
});

test("a failed migration gets a draft body that says so", () => {
  const failed = outcome({
    status: "failed-validation",
    validation: {
      passed: false,
      checks: [
        { name: "residual usage", passed: false, details: "shipping/client.py:53 still calls it" },
      ],
    },
  });
  const body = prBody({ config: parseConfig(undefined, "/repo"), outcome: failed });
  assert.match(body, /did not fully validate/);
  assert.match(body, /status: `failed-validation`/);
  assert.match(body, /❌ failed/);
  assert.match(body, /still calls it/);
});

test("without a patch, no pull request is attempted", async () => {
  const result = await openPullRequest({
    config: parseConfig(undefined, os.tmpdir()),
    outcome: outcome({ patch: undefined, patchFile: undefined }),
  });
  assert.equal(result.created, false);
  assert.match(result.skipped ?? "", /no patch/);
});

test("outside a git repository it degrades gracefully", async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "acb-pr-nogit-"));
  tempDirs.push(root);
  // Not a git repo: openPullRequest must decline rather than throw.
  const result = await openPullRequest({
    config: parseConfig(undefined, root),
    outcome: outcome(),
  });
  assert.equal(result.created, false);
  assert.match(result.skipped ?? "", /not a git repository|gh CLI/);
});

test("nothing in acb can merge, auto-merge or push to the default branch", async () => {
  // The promise "acb never merges" is only worth making if the code cannot.
  const { stdout: files } = await execFileAsync("find", [SRC, "-name", "*.ts"]);
  const sources = files.trim().split("\n");
  assert.ok(sources.length > 10);

  // Patterns that would be an actual call, not prose about one: the PR body
  // and the docs are allowed to promise this, the code must make it true.
  const forbidden: [RegExp, string][] = [
    [/["'`]merge["'`]/, 'a "merge" argument'],
    [/enableAutoMerge|mergePullRequest|merge_pull_request/i, "a merge API call"],
    [/--auto\b/, "gh pr merge --auto"],
    [/--admin\b/, "gh --admin"],
    [/\bmerge\s*\(/, "a merge() call"],
    [/push[^\n]*["'`](main|master)["'`]/, "a push to the default branch"],
  ];

  for (const file of sources) {
    const code = fs.readFileSync(file, "utf8");
    for (const [pattern, what] of forbidden) {
      assert.doesNotMatch(code, pattern, `${path.basename(file)} must not contain ${what}`);
    }
  }
});
