// Delivering a migration for review.
//
// The patch is always written. With --pr, acb also puts it on a branch and
// opens a pull request through the `gh` CLI.
//
// The hard rule of this file: it can create and update a pull request and
// nothing else. There is no merge call, no auto-merge call, and no push to the
// default branch anywhere in acb — a test greps for that, because "the tool
// will never merge for you" is only worth saying if it cannot.

import { execFile } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { promisify } from "node:util";
import type { Config } from "../config.ts";
import { debug, warn } from "../log.ts";
import type { MigrationOutcome } from "../migrate/index.ts";
import { slug } from "../migrate/index.ts";
import type { ChangeEntry } from "../types.ts";
import { validationSummary } from "../validate/index.ts";

const execFileAsync = promisify(execFile);

export type PrResult = {
  created: boolean;
  url?: string;
  branch: string;
  draft: boolean;
  /** Why no pull request was opened, when that is the case. */
  skipped?: string;
};

export type PrInput = {
  config: Config;
  outcome: MigrationOutcome;
  entries?: ChangeEntry[];
  reportFile?: string;
};

/** `acb/<host>/<date>` — stable enough to update, unique enough not to collide. */
export function branchName(outcome: MigrationOutcome, today = new Date()): string {
  return `acb/${slug(outcome.integrationId.replace(/^https?:/, "").replace(/^http:/, ""))}/${
    today.toISOString().slice(0, 10)
  }`;
}

export function commitMessage(outcome: MigrationOutcome): string {
  const host = outcome.integrationId.replace(/^\w+:/, "");
  const subject =
    outcome.items.length === 1
      ? `fix(api): migrate ${host} — ${trim(outcome.items[0].summary, 60)}`
      : `fix(api): migrate ${host} (${outcome.items.length} upstream changes)`;

  const body = [
    "",
    ...outcome.items.map((item) => `- ${item.summary}`),
    "",
    outcome.validation ? `Validation: ${validationSummary(outcome.validation)}` : "",
    "",
    "Prepared by acb. Requires human review.",
  ];
  return `${subject}\n${body.join("\n")}`;
}

export function prBody(input: PrInput): string {
  const { outcome } = input;
  const entryById = new Map((input.entries ?? []).map((entry) => [entry.id, entry]));
  const lines: string[] = [];

  lines.push(
    outcome.status === "validated"
      ? "> ⚠️ **Generated by acb** — an upstream API change was detected, migrated and " +
          "validated automatically. **A human must review this before merging.**"
      : "> ⚠️ **Generated by acb, and it did not fully validate** (" +
          `status: \`${outcome.status}\`). Opened as a draft so the analysis is not lost. ` +
          "**Needs a human to finish it.**",
  );
  lines.push("");

  lines.push(`## What changed upstream (\`${outcome.integrationId}\`)`);
  lines.push("");
  for (const item of outcome.items) {
    const entry = entryById.get(item.entryId);
    lines.push(`### ${item.summary}`);
    lines.push("");
    lines.push(`- Risk: **${item.risk}**${item.deadline ? ` · deadline **${item.deadline}**` : ""}`);
    if (entry?.source) lines.push(`- Source: ${entry.source}`);
    lines.push(`- Assessed by: ${item.analyzedBy}`);
    if (item.whatChanged) {
      lines.push("");
      lines.push(trim(item.whatChanged, 1200));
    }
    if (item.affected.length) {
      lines.push("");
      lines.push("Affected here:");
      for (const location of item.affected.slice(0, 10)) {
        lines.push(`- \`${location.file}:${location.line}\` — ${location.reason}`);
      }
    }
    lines.push("");
  }

  lines.push("## What this pull request does");
  lines.push("");
  lines.push(outcome.summary || "(the agent gave no summary)");
  lines.push("");
  if (outcome.changedFiles.length) {
    lines.push("Files changed:");
    for (const file of outcome.changedFiles) lines.push(`- \`${file}\``);
    lines.push("");
  }

  lines.push("## Validation");
  lines.push("");
  if (outcome.validation) {
    lines.push("| Check | Result |");
    lines.push("| --- | --- |");
    for (const check of outcome.validation.checks) {
      lines.push(`| ${check.name} | ${check.passed ? "✅ passed" : "❌ failed"} |`);
    }
    lines.push("");
    for (const check of outcome.validation.checks.filter((c) => !c.passed)) {
      lines.push(`<details><summary>${check.name}</summary>`);
      lines.push("");
      lines.push("```");
      lines.push(trim(check.details, 3000));
      lines.push("```");
      lines.push("");
      lines.push("</details>");
      lines.push("");
    }
  } else {
    lines.push("No validation result was recorded.");
    lines.push("");
  }

  lines.push("## How to check this yourself");
  lines.push("");
  lines.push("```sh");
  for (const command of outcome.items.length ? input.config.validate.commands : []) {
    lines.push(command);
  }
  lines.push(`node bin/acb contract ${outcome.integrationId}`);
  lines.push("```");
  lines.push("");
  lines.push(
    `The full impact report and the agent's tool-by-tool transcript are in \`.acb/\`` +
      `${input.reportFile ? ` (\`${path.basename(input.reportFile)}\`)` : ""}.`,
  );
  lines.push("");
  lines.push("<sub>acb does not merge, enable auto-merge, or push to the default branch.</sub>");

  return lines.join("\n");
}

export async function openPullRequest(input: PrInput): Promise<PrResult> {
  const { config, outcome } = input;
  const branch = branchName(outcome);
  const draft = outcome.status !== "validated";
  const result: PrResult = { created: false, branch, draft };

  if (!outcome.patch) return { ...result, skipped: "there is no patch to propose" };

  const git = (args: string[]) => execFileAsync("git", args, { cwd: config.root });

  try {
    await git(["rev-parse", "--git-dir"]);
  } catch {
    return { ...result, skipped: `${config.root} is not a git repository` };
  }
  if (!(await hasGhCli())) {
    return {
      ...result,
      skipped: "the gh CLI is not available; the patch was written instead",
    };
  }

  const startingPoint = (await git(["rev-parse", "--abbrev-ref", "HEAD"])).stdout.trim();
  try {
    // Work on a branch from the current HEAD; the user's checkout is restored
    // in the finally block whatever happens.
    const branchExists = await exists(git, branch);
    await git(branchExists ? ["checkout", branch] : ["checkout", "-b", branch]);

    await execFileAsync("git", ["apply", "--3way", outcome.patchFile!], { cwd: config.root });
    await git(["add", "-A"]);
    await git(["commit", "--no-gpg-sign", "-m", commitMessage(outcome)]);
    await git(["push", "--set-upstream", "origin", branch]);

    const bodyFile = path.join(config.root, ".acb", `pr-body-${slug(outcome.integrationId)}.md`);
    fs.mkdirSync(path.dirname(bodyFile), { recursive: true });
    fs.writeFileSync(bodyFile, prBody(input));

    const existingUrl = await existingPrUrl(config.root, branch);
    if (existingUrl) {
      // Updating beats opening a second pull request for the same branch.
      await gh(config.root, [
        "pr",
        "edit",
        branch,
        "--title",
        commitMessage(outcome).split("\n")[0],
        "--body-file",
        bodyFile,
      ]);
      debug(`updated ${existingUrl}`);
      return { ...result, created: true, url: existingUrl };
    }

    const args = [
      "pr",
      "create",
      "--head",
      branch,
      "--title",
      commitMessage(outcome).split("\n")[0],
      "--body-file",
      bodyFile,
      "--label",
      "api-migration",
      "--label",
      `risk:${highestRisk(outcome)}`,
    ];
    if (draft) args.push("--draft");

    const { stdout } = await gh(config.root, args);
    const url = stdout.trim().split("\n").at(-1);
    return { ...result, created: true, url };
  } catch (err) {
    warn(`could not open a pull request: ${(err as Error).message}`);
    return { ...result, skipped: (err as Error).message };
  } finally {
    try {
      await git(["checkout", startingPoint]);
    } catch (err) {
      warn(`could not return to ${startingPoint}: ${(err as Error).message}`);
    }
  }
}

function highestRisk(outcome: MigrationOutcome): string {
  if (outcome.items.some((item) => item.risk === "high")) return "high";
  if (outcome.items.some((item) => item.risk === "medium")) return "medium";
  return "low";
}

async function hasGhCli(): Promise<boolean> {
  try {
    await execFileAsync("gh", ["--version"]);
    return true;
  } catch {
    return false;
  }
}

async function exists(
  git: (args: string[]) => Promise<unknown>,
  branch: string,
): Promise<boolean> {
  try {
    await git(["rev-parse", "--verify", branch]);
    return true;
  } catch {
    return false;
  }
}

async function existingPrUrl(cwd: string, branch: string): Promise<string | undefined> {
  try {
    const { stdout } = await gh(cwd, ["pr", "list", "--head", branch, "--json", "url", "--limit", "1"]);
    const parsed = JSON.parse(stdout) as { url?: string }[];
    return parsed[0]?.url;
  } catch {
    return undefined;
  }
}

function gh(cwd: string, args: string[]) {
  return execFileAsync("gh", args, { cwd, maxBuffer: 5 * 1024 * 1024 });
}

function trim(text: string, length: number): string {
  const clean = text.trim();
  return clean.length > length ? clean.slice(0, length - 1) + "…" : clean;
}
